name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: coursier/setup-action@v1
      with:
        jvm: adopt:11
        apps: scala
    - name: Run tests
      run: ./gradlew allJar && scala -jar build/libs/shadow-jar.jar
